TASK 1

In [5]:
import pandas as pd

In [11]:
df=pd.read_csv("vgsalesGlobale.csv")

df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [15]:
totalsales = df["Global_Sales"].sum()
print("Total Sales : ", totalsales)

Total Sales :  8920.44


In [23]:
highestgame = df[df["Global_Sales"] == df["Global_Sales"].max()]
highestgame


Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74

In [41]:
avgsaleNA=df["NA_Sales"].mean()
avgsaleEU=df["EU_Sales"].mean()
avgsaleJP=df["JP_Sales"].mean()
avgsaleother=df["Other_Sales"].mean()


print("Average Sale in NA : ", avgsaleNA)
print("Average Sale in EU : ", avgsaleEU)
print("Average Sale in JP : ", avgsaleJP)
print("Average Sale in Others : ", avgsaleother)

Average Sale in NA :  0.26466742981082064
Average Sale in EU :  0.14665200626581515
Average Sale in JP :  0.077781660441017
Average Sale in Others :  0.0480630196409206


In [51]:
Top5 = df.groupby("Genre")["Global_Sales"].sum().nlargest(5)
print("Top 5 Generes are :\n", Top5)

Top 5 Generes are :
 Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [57]:
TotalSalesByGenre = df.groupby("Genre")[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].sum()
print("Total Sales By Genre :", TotalSalesByGenre)

Total Sales By Genre :               NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


In [61]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [63]:
TopPlateforms = df.groupby("Platform")["Global_Sales"].sum().nlargest(3)
print("Top 3 Plateforms : ", TopPlateforms)

Top 3 Plateforms :  Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [73]:
TotalSales = df["Global_Sales"].sum()
MarketShare = (df.groupby("Genre")["Global_Sales"].sum() / TotalSales) * 100

print("Market Share : ", MarketShare)

Market Share :  Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [75]:
corr = df["NA_Sales"].corr(df["EU_Sales"])

print("Correlation Between NA_Sales and Eu_Sales is : ", corr)

Correlation Between NA_Sales and Eu_Sales is :  0.7677267483702629


TASK 2

In [91]:
dic={
    "hello": "hi",
    "goodbye": "bye",
    "how": "aa",
    "are": "bb",
    "you": "ac",
    "what": "xy",
    "doing": "yz",
    "time": "xz"
}

In [95]:
word = input("Enter word in English to Translate : ")

if word in dic:
    print(word, " in Spanish is : ", dic[word])
else:
    print("The Given word is not present in dictionary")

Enter word in English to Translate :  are


are  in Spanish is :  bb


In [97]:
while True:
    word = input("Enter word in English to Translate to exit loop type exit : ").lower()

    if word == "exit":
        print("Exitting from Loop....")
        break  

    if word in dic:
        print(word, " In Spanish is : ", dic[word])
    else:
        print("The Given word is not present in dictionary")

Enter word in English to Translate to exit loop type exit :  are


are  In Spanish is :  bb


Enter word in English to Translate to exit loop type exit :  is


The Given word is not present in dictionary


Enter word in English to Translate to exit loop type exit :  how


how  In Spanish is :  aa


Enter word in English to Translate to exit loop type exit :  exit


Exitting from Loop....


TASK 3

In [129]:
impmails = []
prommails = []
spammails = []

def classifyemails(emails):
    imp_keys = ["a", "b", "c", "d", "e"]
    prom_keys = ["f", "g", "h", "i", "j", "k"]
    spam_keys = ["l", "m", "n", "o", "p", "q"]

    

    for x in emails:
        email_lower = x.lower() 
        if any(word in email_lower for word in imp_keys):
            impmails.append(x)
        elif any(word in email_lower for word in prom_keys):
            prommails.append(x)
        elif any(word in email_lower for word in spam_keys):
            spammails.append(x)

    return impmails, prommails, spammails

mails = ["Hello a", "HI b", "How l", "is d", "the i", "Weather o", "whats c", "Up x"]

a, b, c = classifyemails(mails)

print("Important Mails : ", a)
print("\nPromotions Mails : ", b)
print("\nSpam Mails : ", c)



Important Mails :  ['Hello a', 'HI b', 'is d', 'the i', 'Weather o', 'whats c']

Promotions Mails :  ['How l']

Spam Mails :  ['Up x']


TASK 4

In [143]:
products = {
    1: "Bread",
    2: "Butter",
    3: "Eggs",
    4: "Milk",
    5: "Apples"
}

cart = []

print("Welcome to the Store")
print("Available Products are :")

for key, value in products.items():
    print(f"{key}. {value}")
while 1:
    choice = input("Enter The Serial Number of Product You Want to Buy To Exit Press q  : ").lower()
    
    if choice == '1':
        cart.append(products[1])
    elif choice == '2':
        cart.append(products[2])
    elif choice == '3':
        cart.append(products[3])
    elif choice == '4':
        cart.append(products[4])
    elif choice == '5':
        cart.append(products[5])
    elif choice == 'q':
        break
    else:
        print("Input in not Correct. Enter Valid Number Or Press Q.....")

print("\nYour Shopping Cart is :")

if cart:
    for item in cart:
        print(item)
else:
    print("\nYour cart is empty.")

# Goodbye message
print("\n Bye Bye")


Welcome to the Store
Available Products are :
1. Bread
2. Butter
3. Eggs
4. Milk
5. Apples


Enter The Serial Number of Product You Want to Buy To Exit Press q  :  1
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  2
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  3
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  4
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  5
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  6


Input in not Correct. Enter Valid Number Or Press Q.....


Enter The Serial Number of Product You Want to Buy To Exit Press q  :  5
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  4
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  3
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  2
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  1
Enter The Serial Number of Product You Want to Buy To Exit Press q  :  q



Your Shopping Cart is :
Bread
Butter
Eggs
Milk
Apples
Apples
Milk
Eggs
Butter
Bread

 Bye Bye


TASK 5:

In [162]:
import numpy as np

arr1=np.array([1, 2, 3, 4, 5, 6])
arr2=np.array([7, 8, 9, 10, 11, 12])

sumarr=arr1+arr2
print("Addition : ", sumarr)

prodarr=arr1*arr2
print("Multiplication : ", prodarr)


Addition :  [ 8 10 12 14 16 18]
Multiplication :  [ 7 16 27 40 55 72]


TASK 6:

In [173]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr1 = arr.reshape(3, 4)
print("Reshaped Array : \n", arr1)

arr2=np.array([1, 2, 3, 4, 5, 6])
arr3=np.array([7, 8, 9, 10, 11, 12])

vertical=np.vstack((arr2, arr3))
horizontal=np.hstack((arr2,arr3))

print("\nVertical Concatination : \n", vertical)
print("\nHorizontal Concatination : \n",horizontal)

Reshaped Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Vertical Concatination : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Horizontal Concatination : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


TASK 7

In [176]:
arr = [1, 2, 3, 4, 5, 6]

arr1 = arr[::-1]

print("List After Reversing : ", arr1)


List After Reversing :  [6, 5, 4, 3, 2, 1]
